FROM python:3.13-alpine

RUN apk --no-cache add \
    # funani dependencies
    file \
    # Pillow dependencies
    freetype \
    fribidi \
    harfbuzz \
    jpeg \
    lcms2 \
    openjpeg \
    tcl \
    tiff \
    tk \
    # TODO: remote this once UTC is used consistently
    tzdata \
    zlib

# HACK:
# precedently used metadata is using this timezone need to
# convert to UTC inside the metadata
ENV TZ=Europe/Berlin

WORKDIR /home

RUN pip install --upgrade pip && \
    pip install poetry

COPY pyproject.toml poetry.* ./
RUN poetry install

RUN mkdir -p /data

WORKDIR /code

COPY src .

ENV PATH=/root/.local:$PATH

ENTRYPOINT [ "python", "./funani.py" ]
CMD ["--help"]
