version: "3.3"
services:
  db:
    container_name: funani-db
    restart: always
    image: funani-db
    build:
      context: ./db
    volumes:
      - funani-db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 5432:5432

  graphql:
    container_name: funani-graphql
    restart: always
    image: funani-graphql
    build:
      context: ./graphql
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - network
    ports:
      - 5433:5433

networks:
  network:

volumes:
  funani-db:
